[tool.black]
exclude = '''
^/(
  (
    # root directories to exclude
    \.DS_Store
    | \.conan
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.vs
    | \.vscode
    | _venv
  )/
  # any rooted files to ignore would go here
)
# unrooted paths here
| __pycache__/
'''
experimental-string-processing = true
preview = true
line-length = 88

[tool.isort]
profile = 'black'
lines_between_types = 1
combine_as_imports = true
line_length = 88

[tool.ruff]
line-length = 88
ignore = [
    "E402",  # Module level import not at top of file
]